#pragma once

#define TEDAVR_DUALSHOCK2_EXPRESSION_SS_PIN 2
#define TEDAVR_DUALSHOCK2_EXPRESSION_SCK_PIN 5
#define TEDAVR_DUALSHOCK2_EXPRESSION_MOSI_PIN 3
#define TEDAVR_DUALSHOCK2_EXPRESSION_MISO_PIN 4
#define TEDAVR_DUALSHOCK2_EXPRESSION_SS_DDR DDRB
#define TEDAVR_DUALSHOCK2_EXPRESSION_SCK_DDR DDRB
#define TEDAVR_DUALSHOCK2_EXPRESSION_MOSI_DDR DDRB
#define TEDAVR_DUALSHOCK2_EXPRESSION_MISO_DDR DDRB

#define TEDAVR_DUALSHOCK2_EXPRESSION_SPICONTROL_RESET SPCR = 0x00
#define TEDAVR_DUALSHOCK2_EXPRESSION_SPICONTROL_MASTERMODE SPCR |= _BV(MSTR)
#define TEDAVR_DUALSHOCK2_EXPRESSION_SPICONTROL_CLOCKHIGHIDLE SPCR |= _BV(CPOL)
#define TEDAVR_DUALSHOCK2_EXPRESSION_SPICONTROL_TRAILSAMPLE SPCR |= _BV(CPHA)
#define TEDAVR_DUALSHOCK2_EXPRESSION_SPICONTROL_LSBFIRST SPCR |= _BV(DORD)
#define TEDAVR_DUALSHOCK2_EXPRESSION_SPICONTROL_PRESCALESET SPCR |= _BV(SPI2X) | _BV(SPR1)
#define TEDAVR_DUALSHOCK2_EXPRESSION_SPICONTROL_ENABLE SPCR |= _BV(SPE)

#define TEDAVR_DUALSHOCK2_EXPRESSION_SPIOUT SPDR

#define TEDAVR_DUALSHOCK2_EXPRESSION_TRANSMISSIONINCOMPLETE !(SPSR & _BV(SPIF))
